version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm start
      - echo "npm start normally"
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - src/*
  discard-paths: yes
  name: js-app-$(date +%Y-%m-%d-%H-%M-%S).zip